#!/usr/bin/env bash
# SpeedyFiles bare-metal installer
#
# Usage:  curl -fsSL https://speedyfiles.app/install.sh | sudo bash
#         OR  sudo ./install.sh
#
# Installs to /opt/speedyfiles, creates a service user, runs the app under
# systemd. Does NOT touch nginx or TLS — point your existing reverse proxy
# at 127.0.0.1:5300.

set -euo pipefail

INSTALL_DIR=${INSTALL_DIR:-/opt/speedyfiles}
DATA_DIR=${DATA_DIR:-/var/lib/speedyfiles}
FILES_DIR=${FILES_DIR:-/srv/files}
SERVICE_USER=${SERVICE_USER:-speedyfiles}
REPO_URL=${REPO_URL:-https://github.com/speedyfiles/speedyfiles.git}
GIT_REF=${GIT_REF:-main}

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
note() { printf "  → %s\n" "$1"; }

if [[ $EUID -ne 0 ]]; then
  echo "Run as root (or via sudo)" >&2; exit 1
fi

bold "[1/7] Checking prerequisites"
for cmd in git python3 systemctl openssl; do
  command -v $cmd >/dev/null || { echo "missing: $cmd"; exit 1; }
done
PYVER=$(python3 -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")')
note "python3 ($PYVER), git, systemctl, openssl: present"

bold "[2/7] Service user"
if ! id "$SERVICE_USER" &>/dev/null; then
  useradd --system --no-create-home --shell /usr/sbin/nologin \
          --home-dir "$INSTALL_DIR" --user-group "$SERVICE_USER"
  note "created user $SERVICE_USER"
else
  note "user $SERVICE_USER already exists"
fi

bold "[3/7] Code"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  note "updating existing checkout at $INSTALL_DIR"
  git -C "$INSTALL_DIR" fetch --quiet origin
  git -C "$INSTALL_DIR" checkout --quiet "$GIT_REF"
  git -C "$INSTALL_DIR" pull --quiet --ff-only
else
  note "cloning $REPO_URL → $INSTALL_DIR"
  git clone --depth 1 --branch "$GIT_REF" "$REPO_URL" "$INSTALL_DIR"
fi

bold "[4/7] Python venv + deps"
if [[ ! -d "$INSTALL_DIR/.venv" ]]; then
  python3 -m venv "$INSTALL_DIR/.venv"
fi
"$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade pip wheel
"$INSTALL_DIR/.venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"
note "deps installed"

bold "[5/7] Directories + .env"
mkdir -p "$DATA_DIR" "$FILES_DIR"
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR" "$DATA_DIR" "$FILES_DIR"
chmod 0750 "$DATA_DIR" "$FILES_DIR"
if [[ ! -f "$INSTALL_DIR/.env" ]]; then
  SECRET=$(openssl rand -hex 32)
  cat > "$INSTALL_DIR/.env" <<EOF
# SpeedyFiles configuration (auto-generated by install.sh)
SESSION_SECRET=$SECRET
PUBLIC_BASE_URL=http://localhost:5300
DATABASE_URL=sqlite+aiosqlite:///$DATA_DIR/app.db
STORAGE_BACKEND=local
LOCAL_STORAGE_ROOT=$FILES_DIR
APP_NAME=SpeedyFiles
DEBUG=false
EOF
  chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/.env"
  chmod 0640 "$INSTALL_DIR/.env"
  note ".env generated at $INSTALL_DIR/.env"
  note "Edit PUBLIC_BASE_URL when you have a real hostname"
else
  note ".env already exists; not overwriting"
fi

bold "[6/7] Database"
sudo -u "$SERVICE_USER" "$INSTALL_DIR/.venv/bin/python" -m app.cli init-db
note "schema initialized at $DATA_DIR/app.db"

bold "[7/7] systemd unit"
SERVICE_FILE=/etc/systemd/system/speedyfiles.service
sed -e "s|/opt/speedyfiles|$INSTALL_DIR|g" \
    -e "s|speedyfiles\\.service|speedyfiles.service|" \
    "$INSTALL_DIR/deploy/systemd/speedyfiles.service.template" > "$SERVICE_FILE"
systemctl daemon-reload
systemctl enable --now speedyfiles
sleep 2
if curl -fsS -o /dev/null http://127.0.0.1:5300/healthz; then
  note "service is healthy on 127.0.0.1:5300"
else
  note "service not reachable yet — check 'journalctl -u speedyfiles -n 30'"
fi

bold "Done"
cat <<EOF

Next steps:
  1. Visit http://<this-host>:5300/setup and create your admin account.
  2. Put a reverse proxy with TLS in front (see deploy/nginx/).
  3. Configure mail under Settings → Mail.

Service control:
  systemctl status speedyfiles
  journalctl -u speedyfiles -f

Paths:
  App:    $INSTALL_DIR
  Data:   $DATA_DIR
  Files:  $FILES_DIR
EOF
